version: "3.8"

services:
  app:
    build: .
    image: ticket-system-frontend
    volumes:
      - ./frontend:/code
      - notused:/code/node_modules
    stdin_open: true
    ports:
      - 3000:3000
    command: npm start

volumes:
  notused: